const SHOW_EXAMPLE_BOOTSTRAP = 'SHOW_EXAMPLE_BOOTSTRAP';
const SHOW_EXAMPLE_REACT = 'SHOW_EXAMPLE_REACT';
const SHOW_EXAMPLE_VUE = 'SHOW_EXAMPLE_VUE';
const SHOW_EXAMPLE = 'SHOW_EXAMPLE';
const SET_MARKDOWN = 'SET_MARKDOWN';
const SET_DOC_NAME = 'SET_DOC_NAME';
const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR';
const NEW_DOC = 'NEW_DOC';
const SAVE_DOC = 'SAVE_DOC';
const REMOVE_DOC = 'REMOVE_DOC';
const GET_DOC = 'GET_DOC';
const GET_ALL_DOCS = 'GET_ALL_DOCS';
const SET_LIST = 'SET_LIST';
const SET_REV = 'SET_REV';
const SELECT_EXSITING_DOC = 'SELECT_EXSITING_DOC';
const SHOW_MODAL = 'SHOW_MODAL';
const HIDE_MODAL = 'HIDE_MODAL';
const GET_SEARCH_USER_ASYNC = 'GET_SEARCH_USER_ASYNC';
const GET_SEARCH_USER = 'GET_SEARCH_USER';
const LOADING = 'LOADING';
const SHOW_RESULT = 'SHOW_RESULT';

export default {
  SHOW_EXAMPLE_BOOTSTRAP,
  SHOW_EXAMPLE_REACT,
  SHOW_EXAMPLE_VUE,
  SHOW_EXAMPLE,
  SET_MARKDOWN,
  SET_DOC_NAME,
  TOGGLE_SIDEBAR,
  NEW_DOC,
  SAVE_DOC,
  GET_DOC,
  GET_ALL_DOCS,
  SET_LIST,
  SELECT_EXSITING_DOC,
  SHOW_MODAL,
  HIDE_MODAL,
  REMOVE_DOC,
  SET_REV,
  GET_SEARCH_USER_ASYNC,
  GET_SEARCH_USER,
  LOADING,
  SHOW_RESULT
}
