const SHOW_EXAMPLE_BOOTSTRAP = 'SHOW_EXAMPLE_BOOTSTRAP';
const SHOW_EXAMPLE_REACT = 'SHOW_EXAMPLE_REACT';
const SHOW_EXAMPLE_VUE = 'SHOW_EXAMPLE_VUE';
const SHOW_EXAMPLE = 'SHOW_EXAMPLE';
const SET_MARKDOWN = 'SET_MARKDOWN';
const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR';
const NEW_DOC = 'NEW_DOC';

export default {
  SHOW_EXAMPLE_BOOTSTRAP,
  SHOW_EXAMPLE_REACT,
  SHOW_EXAMPLE_VUE,
  SHOW_EXAMPLE,
  SET_MARKDOWN,
  TOGGLE_SIDEBAR,
  NEW_DOC
}
